### ISSUE TITLE
Migrate from Travis CI to GA

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#109]
Checkout `action-rs` repo for available actions.

**Comment by mark-stopka** [comment]
@pavlix are you familiar with CI/CD pipelines? I may do the migration, but would prefer your do it and learn a bit abut GitHub Actions and CI/CD workflows...

T&C as agreed, or dCloud Discord / mail...

**Comment by greenhat** [comment]
Done in #155
