### ISSUE TITLE
Add missing ErgoTree IR nodes (serialization, evaluation)

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#14]
List if missing nodes is in [ergotree-ir/README.md](https://github.com/ergoplatform/sigma-rust/tree/develop/ergotree-ir)

Create new struct in a separate module(file) in `mir` module and add it to `Expr` enum.

### Serialization
- Implement `SigmaSerializable` trait and add node's op code in `serialization::expr`;
- Implement `Arbitrary` trait and add serialization roundtrip PBT test for this node;

### Evaluation
- Implement `Evaluable` trait in `ergotree-interpreter` crate;
- Add evaluation tests;

Checkout implemented IR nodes (`Fold`, `ByIndex`) for implementation details.

**Comment by Ch1n3du** [comment]
Hi, I wanted to ask if this issue is still open. I would like to handle it.
