### ISSUE TITLE
Ensure JSON from explorer API is parsed properly

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#152]
### Motivation
Node and explorer use slightly different names for the same fields. For example `id` vs `boxId` for box ids, `transactionId` vs `txId` for transaction id in box, which are handled as aliases in serde.

### Fix
Find all field names that have the same meaning but different names in explorer vs node API. Use serde alias to handle different names for the same field. See [example](https://github.com/ergoplatform/sigma-rust/blob/json-error-transactionid/ergo-lib/src/chain/json.rs#L74)
One way to find the differences is to compare `openapi.yml`.
Node: https://github.com/ergoplatform/ergo/blob/develop/src/main/resources/api/openapi.yaml
Explorer: https://api.ergoplatform.com/docs/openapi

**Comment by kettlebell** [comment]
I've been looking at Explorer and I see that the API is current v1. The names for this version appear to be in line with the node and I will double-check them. It's v0 that has the different names. Should we support v0 too?

**Comment by greenhat** [comment]
> I've been looking at Explorer and I see that the API is currently v1. The names for this version appear to be consistent with the node and I will double-check them. It's v0 that has the different names. Should we support v0 too?

Good question! I believe v0 is still in use and we need to support it. 

BTW, I added more "help wanted" labels.

**Comment by kettlebell** [comment]
Got that, thanks for that and the labels.
