### ISSUE TITLE
Implement ContextExtension serialization (+JSON)

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#18]

**Comment by jasondavies** [comment]
I had a quick look at implementing this. I think this requires full value serialisation support for each item value.

**Comment by greenhat** [comment]
@jasondavies Yes, you're right. I was too quick with "good first issue" label.

**Comment by jasondavies** [comment]
To be fair, if we have some simple value types that can be (de)serialised (let's say numbers to start with), we can fail if an unsupported value type is (de)serialised.
