### ISSUE TITLE
Check for allowed ops in Coll.flatmap lambda

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#222]
See the check in sigmastate - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/2cb966eac2c763e3aa7f344ca1c77384fb1fc056/sigmastate/src/main/scala/sigmastate/types.scala#L1423-L1496

Should be checked on Coll.flatmap evaluation.

**Comment by ross-weir** [comment]
I'm looking into this one
