### ISSUE TITLE
[300 SigmaUSD] Sigma protocol implementation for AtLeast

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#248]
Implemented in #377:
- ~~evaluation(exept `Cthreshold::reduce`);~~
- ~~prover(exept Gf2_192*);~~
- ~~verifier;~~

Todo:
- #473
- ~~implement `Cthreshold::reduce` [Scala reference impl](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/262a14d17ae3090fa97d1de1effd0b338562e4db/sigmastate/src/main/scala/sigmastate/trees.scala#L467-L518);~~ #482
- ~~test verifier with proofs from mainnet/sigmastate [Scala test vector](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/262a14d17ae3090fa97d1de1effd0b338562e4db/sigmastate/src/test/scala/sigmastate/crypto/SigningSpecification.scala#L119-L135);~~ #535 
- test prover with verifier by generating arbitrary `AtLeast` IR node proving it and then passing through the verifier (see `verifier::tests` for examples);

**Comment by ross-weir** [comment]
I'm starting on this one 👍

**Comment by greenhat** [comment]
> I'm starting on this one 👍

Great! Please be aware that #473 is needed for testing prover/verifier.

**Comment by greenhat** [comment]
@ross-weir Hey! #473 is implemented and merged. Everything is in place to finish this task.

**Comment by ross-weir** [comment]
> @ross-weir Hey! #473 is implemented and merged. Everything is in place to finish this task.

Thanks, restarting this one

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
