### ISSUE TITLE
Transacrion in block 400188 fails to roundtrip

### ISSUE THREAD

**Issue by Shimuuar** [ergoplatform/sigma-rust#249]
Namely [this one](https://explorer.ergoplatform.com/en/transactions/9da0ea07e4f859b6a71817d9ccb67f43ddfa1f8a59f7cf2af18a544bcd799706). Offending ergo tree is: `1000d1ed8503` which deserialized as
```
BoolToSigmaProp(
    BoolToSigmaProp {
        input: BinOp(
            BinOp {
                kind: Relation(
                    And,
                ),
                left: Const(
                    Constant {
                        tpe: SBoolean,
                        v: Boolean(false,),
                    },
                ),
                right: Const(
                    Constant {
                        tpe: SBoolean,
                        v: Boolean(false,),
                    },
                ),
            },
        ),
    },
)
```

I suspect problem is in `ReadSigmaVlqExt::get_bits`. I it decodes bit vector in MST while it should use LSB instead.

**Comment by greenhat** [comment]
Yep, looks like the case. We're using `bit-vec` crate which seems to be only offering MSB. There is `bitvec` crate that might have LSB.
