### ISSUE TITLE
Consider an array with const generic (length) for STypeCompanion::methods

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#250]

**Comment by kettlebell** [comment]
Had a look at this and I don't think we can implement since `STypeCompanion` is now an enum, where each variant corresponds to a different number of method descriptors. So the `length` cannot be determined at compile-time. Am I missing something here?

**Comment by greenhat** [comment]
Yes, you are right. Thank you for looking into this.
