### ISSUE TITLE
Are data types for network protocol in scope for this library?

### ISSUE THREAD

**Issue by Shimuuar** [ergoplatform/sigma-rust#278]
What I mean data types for messages and corresponding serialization/parsing code. If so where should they live?

I have half done implementation for that. So question really is whether I should gradually fold it into this library or keep it separate

**Comment by greenhat** [comment]
It definitely deserves its own library. The goal for libraries in this repo is to serve as tools/helpers to build on top of the existing node/explorer/etc. ecosystem. 
The network protocol implementation is closer to the internal set of tools used in node, SPV, etc.
I'll be happy to set up a separate repo with CI and stuff for this new lib.

**Comment by greenhat** [comment]
There is also https://github.com/SabaunT/ergo-handshake

**Comment by Shimuuar** [comment]
I think I start by moving into sigma-rust functionality that must live here. Such as header defintion , its enconding/parsing and see how it will affect design of network library

**Comment by greenhat** [comment]
Sounds good!

**Comment by Shimuuar** [comment]
I think most interesting question in API design is serialization part. Right now we have 

```rust
pub trait SigmaSerializable: Sized {
    fn sigma_serialize<W: SigmaByteWrite>(&self, w: &mut W) -> Result<(), io::Error>;
    fn sigma_parse<R: SigmaByteRead>(r: &mut R) -> Result<Self, SerializationError>;
    ...
}
```

It's very nice. Only problem is `SigmaByteRead`/`SigmaByteWrite`. Those are needed for parsing of ergoscript but aren't for basically everything else. It's also impossible to use with types that only implement `io::Read` such is `TcpStream`. So I'd say problem is how to disentangle common serialization patterns in ergo and logic specific to transactions.


One approach I can imagine is to define another similar trait and blanket implementation

```rust
pub trait ErgoSerializable: Sized {
    fn ergo_serialize<W: WriteSigmaVlqExt>(self, w: &mut W) -> Result<(), io::Error>;
    fn ergo_parse<R: ReadSigmaVlqExtr: &mut R) -> Result<Self, SerializationError>;
    ...
}

impl<T: ErgoSerializable> SigmaSerializable for T {
  ...
}
```
This of course conflicts with current blanket implementation.

**Comment by greenhat** [comment]
> I think most interesting question in API design is serialization part. Right now we have
> 
> ```rust
> pub trait SigmaSerializable: Sized {
>     fn sigma_serialize<W: SigmaByteWrite>(&self, w: &mut W) -> Result<(), io::Error>;
>     fn sigma_parse<R: SigmaByteRead>(r: &mut R) -> Result<Self, SerializationError>;
>     ...
> }
> ```
> 
> It's very nice. Only problem is `SigmaByteRead`/`SigmaByteWrite`. Those are needed for parsing of ergoscript but aren't for basically everything else. It's also impossible to use with types that only implement `io::Read` such is `TcpStream`. So I'd say problem is how to disentangle common serialization patterns in ergo and logic specific to transactions.
> 
> One approach I can imagine is to define another similar trait and blanket implementation
> 
> ```rust
> pub trait ErgoSerializable: Sized {
>     fn ergo_serialize<W: WriteSigmaVlqExt>(self, w: &mut W) -> Result<(), io::Error>;
>     fn ergo_parse<R: ReadSigmaVlqExtr: &mut R) -> Result<Self, SerializationError>;
>     ...
> }
> 
> impl<T: ErgoSerializable> SigmaSerializable for T {
>   ...
> }
> ```
> 
> This of course conflicts with current blanket implementation.

Yes, I agree, `SigmaByte*` only needed for ErgoTree. But you cannot parse a tx without parsing ErgoTree in tx's boxes. The same goes for serialization. 
I like the idea of splitting the serialization into ErgoTree/Non-ErgoTree parts though. I wonder if we could start to parse the tx with `ReadSigmaVlqExt` reader and wrap it into `SigmaByteRead` when we get to parse the tree in the box. Adding an empty constant store is not an issue, but `Peekable` seems like the major obstacle.

**Comment by greenhat** [comment]
Actually, we might be able to ditch `Peekable` requirement. Only `SType::sigma_parse` will be affected (type code will be passed as a parameter).

**Comment by greenhat** [comment]
Wait, `Peekable` is also used in `BinOp` parsing - https://github.com/ergoplatform/sigma-rust/blob/9b423209319712309d017c0b813e607e6e389874/ergotree-ir/src/serialization/bin_op.rs#L47
And it seems it'd be hard to remove it here.

**Comment by Shimuuar** [comment]
I think it should be possible to wrap reader for transactions to get `SigmaByteRead` since it doesn't need any information about constant etc. Problem is `Peekable`. Generally one can't drop `PeekableReader` once its added. There's nothing that could be done with peeked byte.

I think it should be possible to to drop `Peekable` for binop parsing too. It's a bit hacky. General idea is to add peekable wrapper only if check above failed and since subseqent parsing guaranteed to consume at least one byte it could be dropped after. I'll try to check whether it's workable

**Comment by greenhat** [comment]
> I think it should be possible to to drop `Peekable` for binop parsing too. It's a bit hacky. General idea is to add peekable wrapper only if check above failed and since subseqent parsing guaranteed to consume at least one byte it could be dropped after. I'll try to check whether it's workable

It sounds way better than my initial thought of just reading the byte instead of peeking it and passing it to the interested parties as an additional parameter.

**Comment by Shimuuar** [comment]
> l thought of just reading the byte instead of peeking it and passing it to the interested parties as an additional parameter.

I tried this approach and it's not bad at all. Only `Expr`, `Constant` and ` SType` require adding special handling. That is adding functions like: 
```rust
pub fn parse_with_type_code<R: SigmaByteRead>(r: &mut R, c: TypeCode) -> Result<Self, SerializationError>
```
`sigma_parse` could be then implemented in these terms. And this change allows to kill all peekable stuff. I'll prepare PR shortly

P.S. This is of course about question where to place flaming hoops to jump through. And currently parsing of Expr does involve quite a bit of such jumping
