### ISSUE TITLE
No way to create ConstantStore value

### ISSUE THREAD

**Issue by NCrashed** [ergoplatform/sigma-rust#282]
I cannot find any mean to create `SigmaByteReader` as `ergotree_ir::serialization::constant_store` module is private.

Intended use case:
``` rust
let cursor = Cursor::new(block);
let peekable = PeekableReader::new(cursor);
let reader = SigmaByteReader::new(peekable, ConstantStore::empty());
```

**Comment by greenhat** [comment]
Thanks! Yes, `ConstantStore` should be public. PR is incoming.

**Comment by greenhat** [comment]
@NCrashed Merged. Please check by specifying `develop` branch in your deps.
