### ISSUE TITLE
Type mismatch in coinbase script (MINER_PUBKEY should be a byte array)

### ISSUE THREAD

**Issue by Shimuuar** [ergoplatform/sigma-rust#286]
It contains construct `DecodePoint(MINER_PUBKEY)` but `MINER_PUBKEY` has type `SGroupElement` and `DecodePoint` require input of type `SColl<SByte>`. Someone is clearly in the wrong here.

**Comment by greenhat** [comment]
Yeah, sigma-rust got it wrong. `MINER_PUBKEY` should be a byte array. 
Here is the Scala version - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala#L230-L241

**Comment by greenhat** [comment]
On eval group element should be serialized here - https://github.com/ergoplatform/sigma-rust/blob/e779150b336a1c099204a344387d2c63f880ef1b/ergotree-interpreter/src/eval/global_vars.rs#L16
