### ISSUE TITLE
[50 SigmaUSD] Unify serialization for two-argument ops

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#292]
`TwoArgOp` trait with `arg1` and `arg2` exposed (see `UnaryOp`).
`TwoArgOpTryBuild` trait (see `UnaryOpTryBuild`).

Implement `SigmaSerializable` for any IR nodes that have the above traits implemented. See implementation for `UnaryOp*`.
See reference implementation in Scala - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/serialization/TwoArgumentsSerializer.scala#L15-L25

**Comment by MozarellaMan** [comment]
I was having a look at trying this, but wouldn't this result in conflicting implementations of the `SigmaSerializable` trait? So the compiler would reject it as it is already implemented for `UnaryOp`. For example, if an IR node somehow had the traits `TwoArgOp`, `TwoArgOpTryBuild`, `UnaryOp` and `UnaryOpTryBuild`.

**Comment by Shimuuar** [comment]
One possibility is to use `#[derive(...)]` mechanism. This will require writing some macros though

**Comment by greenhat** [comment]
> I was having a look at trying this, but wouldn't this result in conflicting implementations of the `SigmaSerializable` trait? So the compiler would reject it as it is already implemented for `UnaryOp`. For example, if an IR node somehow had the traits `TwoArgOp`, `TwoArgOpTryBuild`, `UnaryOp` and `UnaryOpTryBuild`.

Good question! I should've put this into the description. We can safely assume that no IR node would implement both TwoArg* and UnaryOp* groups. So for any IR node only one of them will be implemented.

**Comment by MozarellaMan** [comment]
> Good question! I should've put this into the description. We can safely assume that no IR node would implement both TwoArg* and UnaryOp* groups. So for any IR node only one of them will be implemented.

That's what I guessed! Unfortunately if I try to do this it won't compile because of the same reason, conflicting implemntations. I think the compiler prefers things to be forward compatible, even though there will probably be no IR node that implements all four traits at the same time. And you can't specify things like "implement trait for types that have trait X, Y but NOT traits Z,W" (at the moment). So I think this issue might require a different solution, maybe structs that can wrap around a node? Not sure how ergonmic or nice looking it would be though...

Does not compile:

```rust 
struct TwoArgWrapper<T> 
where T: TwoArgOp + TwoArgOpTryBuild
{
    node: T
}

pub trait TwoArgOp {
    /// Input value(expr) of the IR node
    fn input(&self) -> &Expr;
}

pub trait TwoArgOpTryBuild: Sized {
    /// Create new IR node, returns an error if any of the requirements failed
    fn try_build(input: Expr) -> Result<Self, InvalidArgumentError>;
}

impl<T: TwoArgOp + TwoArgOpTryBuild> SigmaSerializable for TwoArgWrapper<T>
{
    fn sigma_serialize<W: SigmaByteWrite>(&self, w: &mut W) -> Result<(), std::io::Error> {
        todo!()
    }

    fn sigma_parse<R: SigmaByteRead>(r: &mut R) -> Result<Self, SerializationError> {
        todo!()
    }
}

**Comment by greenhat** [comment]
@MozarellaMan  Oh, now I get it. I did not think that "conflicting implementation" error would derail this idea. My bad. Thank you for your efforts and for coming up with the wrapper idea, but I'm not sure it's worth the added complexity. I mean these traits were supposed to be implemented only by three IR nodes. They can each implement `SigmaSerializable`.
I'm closing this issue for now. Please, contact me (username greenhat) in our discord https://discord.gg/kj7s7nb to receive the bounty.

**Comment by MozarellaMan** [comment]
No worries! I feel a bit weird about redeeming the bounty since I didn't do any work, I'll have a look at the other issues :)
