### ISSUE TITLE
Rename `UnaryOp*` traits to `OneArgOp*`

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#293]
### Motivation
When introducing similar traits for IR nodes that have two arguments one would expect to name them `BinaryOp*`, but we already have `BinOp` that serves a completely different purpose. Instead, the names `TwoArgOp*` were used in #292. So, in order to be consistent, I suggest we rename `UnaryOp*` traits to `OneArgOp*`.

**Comment by greenhat** [comment]
@Shimuuar What do you think?

**Comment by Shimuuar** [comment]
Overall I deeply apathetic about it, but since BinOp is taken such renaming does make sense
