### ISSUE TITLE
[250 SigmaUSD] Add 256-bit signed integer type and use it for `Value::BigInt`

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#295]
### Motivation
In ErgoTree BigInt is bound to be signed 256-bit integer. Rather than using "unbounded" BigInt and check every time that it still fits into 256-bit it's better to make a new type that is guaranteed to fit in 256-bit.

### Implementation
Similar to existing `BoxValue` and `TokenAmount` types create a new type `BigInt256` wrapping `BigInt`.
Use `BigInt256` in `Value::BigInt()`. 
`BigInt256` should implement only one fallible constructor (`TryFrom`) with bounds checking. Arithmetic ops should be failable as well and check the result for bounds. See `Evaluable` impl for `BinOp` for an example of bounds checking.

**Comment by jerry-best** [comment]
I agree this would be a nice change. I had a quick look at it, and saw a couple options -- one is to wrap BigInt as above, and another would be to try using one of the 256-bit int crates available if they look good. I haven't really looked at it, but this one seemed like it could be useful: https://docs.rs/num256/0.3.1/num256/

**Comment by greenhat** [comment]
> I agree this would be a nice change. I had a quick look at it, and saw a couple options -- one is to wrap BigInt as above, and another would be to try using one of the 256-bit int crates available if they look good. I haven't really looked at it, but this one seemed like it could be useful: https://docs.rs/num256/0.3.1/num256/

Good find! Num256 wraps BigInt (https://github.com/althea-net/num256_rs/blob/48350556b930ac71543a8d068cb31923173f5e9b/src/int256.rs#L18), so it might be exactly what we need here.

**Comment by FitzOReilly** [comment]
I've started working on this.

**Comment by greenhat** [comment]
Done in #325 . Bounty is sent.
