### ISSUE TITLE
[100 SigmaUSD] Implement byte-wise `XOR` op (`|`) for byte arrays

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#296]
Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. 
The constructor should check the types of the arguments (see `Fold::new`, `ByIndex::new`, etc.).

### Serialization
- Implement `SigmaSerializable` trait and add node's op code in `serialization::expr`;
- Implement `Arbitrary` trait and add serialization roundtrip PBT test for this node;

### Evaluation
- Implement `Evaluable` trait in `ergotree-interpreter` crate;
- Add evaluation tests;

Check out existing IR node implementation (`Fold`, `ByIndex`) for details.
Check out the detailed implementation instructions for `Append` op in  #301

Reference Scala version:
IR node and eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/trees.scala#L1045-L1064

**Comment by ApexTheory** [comment]
I have this implemented, hope to finish up the tests tonight and them submit the PR.

**Comment by greenhat** [comment]
Thank you! Bounty is sent.
