### ISSUE TITLE
[150 SigmaUSD] Implement `MultiplyGroup` op for `GroupElement`.

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#298]
Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. 
The constructor should check the types of the arguments (see `Fold::new`, `ByIndex::new`, etc.).

### Serialization
- Implement `SigmaSerializable` trait and add node's op code in `serialization::expr`;
- Implement `Arbitrary` trait and add serialization roundtrip PBT test for this node;

### Evaluation
- Implement `Evaluable` trait in `ergotree-interpreter` crate;
- Add evaluation tests;

Check out existing IR node implementation (`Fold`, `ByIndex`) for details.
Check out the detailed implementation instructions for `Append` op in  #301

Reference Scala version:
IR node and eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/trees.scala#L1087-L1106

**Comment by ApexTheory** [comment]
I have started on this issue.

**Comment by greenhat** [comment]
Done in #316.

**Comment by greenhat** [comment]
Check out your DMs in our discord, please. Your bounty is ready to be sent.

**Comment by greenhat** [comment]
Thank you! Bounty is sent.
