### ISSUE TITLE
[100 SigmaUSD] Implement `CalcSha256` op for byte arrays.

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#299]
Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. 
Implement `UnaryOp` and `UnaryOpTryBuild`.

### Serialization
- Implement `Arbitrary` trait and add serialization roundtrip PBT test for this node;

### Evaluation
- Implement `Evaluable` trait in `ergotree-interpreter` crate;
- Add evaluation tests;

Check out the existing IR node implementation (`CalcBlake2b256`) for details.

Check out the detailed implementation instructions for `Append` op in  #301

Reference Scala version:
IR node and eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/trees.scala#L719-L737

**Comment by qy3u** [comment]
Awesome guide!I'll try this implemention.

**Comment by greenhat** [comment]
> Awesome guide!I'll try this implemention.

Merged. Thank you for your contribution! Please contact me (my username is `greenhat`) on our Discord https://discord.gg/kj7s7nb to receive your bounty.

**Comment by qy3u** [comment]
My discord username is qyu. :)
