### ISSUE TITLE
[200 SigmaUSD] Implement `Slice` op for collection

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#300]
Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. 
The constructor should check the types of the arguments (see `Fold::new`, `ByIndex::new`, etc.).

### Serialization
- Implement `SigmaSerializable` trait and add node's op code in `serialization::expr`;
- Implement `Arbitrary` trait and add serialization roundtrip PBT test for this node;

### Evaluation
- Implement `Evaluable` trait in `ergotree-interpreter` crate;
- Add evaluation tests;

For a more detailed implementation instructions see #301

Check out existing IR node implementation (`Fold`, `ByIndex`) for details.

Reference Scala version:
IR node and eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/utxo/transformers.scala#L81-L111
Serialization - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/serialization/transformers/SliceSerializer.scala#L19-L29

**Comment by FitzOReilly** [comment]
I started working on this. I'll contact you when I'm done or have any questions.

**Comment by FitzOReilly** [comment]
I opened a pull request for this.

**Comment by greenhat** [comment]
Bounty is sent.
