### ISSUE TITLE
[200 SigmaUSD] Implement `Append` op for collection

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#301]
### Semantics
`Append` operation concatenates two collections.

In ErgoScript it's represented as a method on `Collection` instance (e.g. `OUTPUTS.append(INPUTS)`) returning a new collection putting the elements of a passed collection (`INPUTS`) after the elements of target collection (`OUTPUTS`).

### Structure
First, see the reference Scala implementation in - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/utxo/transformers.scala#L60-L79 and check out the implementation of another collection's method `Expr::Fold` to get a taste of how the code is structured in `sigma-rust`.

Let's start with adding `mir::Expr::Append()` enum variant representing IR node along with a struct `Append` in `coll_append` sub-module of `mir` module. We need two fields in this struct to encode the op arguments, one for target collection (`input`) and another for the collection that will be appended (`col2`). Both should be of type `Box<Expr>` meaning expressions that would be evaluated to get the values of both collections later on.
In the `impl` section of `Append` we need a constructor `new` that should check the type of arguments(expressions) (see `Fold::new`). We expect the types of both arguments to be `Coll[T]` (`SType::SColl(_)` in Rust) and the element type for both collections is identical.
Next, we need to define `Append::tpe()` to return the `Append` expression type. Which should be the same as any of the arguments (`input` or `col2`).

### Serialization
To handle serialization we need to implement `HasStaticOpCode` trait (use `OpCode::APPEND`) and `SigmaSerializable` trait for `Append` struct. For the latter see the reference Scala implementation - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/serialization/transformers/AppendSerializer.scala#L15-L23 . To serialize `Append` we need to write both args using their `sigma_serialize` methods. To parse them we need to make Expr::sigma_parse` calls in the same order and use our `Append::new` constructor.
To "plug" our serialization for `Append` IR node into the ErgoTree serialization we need to include our case in `serialization::expr`. While Rust compiler will demand you add a case in `sigma_serialize` we also need to take care of the deserialization part and add our case to `parse_with_tag` (see how cases for other IR nodes are defined there and make a similar one).
To test serialization, we need to implement `Arbitrary` trait and add serialization roundtrip PBT test for `Append` IR node. See `Arbitrary` impl for `Map` to get the idea. Then, add a `proptest` (see `ser_roundtrip` for `Map`) which will do a serialization roundtrip and compare the result to the initial value.

### Evaluation
To handle the evaluation we need to implement `Evaluable` trait for `Append` struct in `ergotree_interpreter::eval::coll_append` module. See the reference Scala implementation in - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/utxo/transformers.scala#L60-L79
First, evaluate both arguments by calling their `eval` implementations. With the resulting two `Value` instances we need to match them as `Value::Coll` going deeper and getting their `CollKind` values and construct a new `Value::Coll` value holding concatenated collections.
To test the evaluation we need to hand-craft ErgoTree with this IR node, evaluate it and compare the result with the result of the semantically equivalent Rust expression. See `ByIndex` test for example - https://github.com/ergoplatform/sigma-rust/blob/7c8c320d1f808d2e5098fcb201dc83634dcd566d/ergotree-interpreter/src/eval/coll_by_index.rs#L70-L79

**Comment by ApexTheory** [comment]
I have begun to take a look at this issue.  I will reach out on Discord when I am closer to checking in my branch.

**Comment by greenhat** [comment]
Merged. Thank you for your contribution! Please contact me (my username is greenhat) on our Discord https://discord.gg/kj7s7nb to receive your bounty.

**Comment by aq-eng** [comment]
I find you on discord.
discord username: aq_eng

**Comment by greenhat** [comment]
Bounty is sent.
