### ISSUE TITLE
[150 SigmaUSD] Implement `Coll.indices` method

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#314]
- Add `SMethod` to `ergotree-ir::types::scoll`(method id is 29); 
- Add `EvalFn` in `ertotree-interpreter::eval::scoll` and include it in `ergotree-interpreter::eval::smethod_eval_fn`

See existing method implementations in `scoll` and `sbox` for examples;

Reference Scala version:
eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/b60edae20f2af3352e4064d139d45a15fc507f7d/library-impl/src/main/scala/special/collection/CollsOverArrays.scala#L74

**Comment by ApexTheory** [comment]
I have started on this issue.

**Comment by greenhat** [comment]
Bounty is sent.
