### ISSUE TITLE
[250 SigmaUSD] Implement `Coll.zip` method

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#329]
- Add `SMethod` to `ergotree-ir::types::scoll`(method id is 14); 
- Add `EvalFn` in `ertotree-interpreter::eval::scoll` and include it in `ergotree-interpreter::eval::smethod_eval_fn`

See existing method implementations in `scoll` and `sbox` for examples;

Reference Scala version:
eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/b60edae20f2af3352e4064d139d45a15fc507f7d/sigmastate/src/main/scala/sigmastate/types.scala#L1655-L1661

**Comment by FitzOReilly** [comment]
I've started working on this.

**Comment by FitzOReilly** [comment]
PR opened: #350

**Comment by greenhat** [comment]
Done in #350 . Bounty is sent.
