### ISSUE TITLE
[150 SigmaUSD] Implement `GroupElement.getEncoded` method

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#330]
- Add `SMethod` to `ergotree-ir::types::sgroup_elem` (method id is 2); 
- Add `EvalFn` in `ertotree-interpreter::eval::sgroup_elem` and include it in `ergotree-interpreter::eval::smethod_eval_fn`

See existing method implementations in `scoll` and `sbox` for examples;

Reference Scala version:
eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/b60edae20f2af3352e4064d139d45a15fc507f7d/sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala#L55
It's just a serialization of `EcPoint`.

**Comment by ApexTheory** [comment]
PR opened https://github.com/ergoplatform/sigma-rust/pull/335

**Comment by greenhat** [comment]
Done in #335. Bounty is sent. Thank you!
