### ISSUE TITLE
[150 SigmaUSD] Implement `GroupElement.negate` method

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#331]
- Add `SMethod` to `ergotree-ir::types::sgroup_elem` (method id is 5); 
- Add `EvalFn` in `ertotree-interpreter::eval::sgroup_elem` and include it in `ergotree-interpreter::eval::smethod_eval_fn`

See existing method implementations in `scoll` and `sbox` for examples;

Reference Scala version:
eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/b60edae20f2af3352e4064d139d45a15fc507f7d/sigma-impl/src/main/scala/special/sigma/TestGroupElement.scala#L18

**Comment by ApexTheory** [comment]
PR opened https://github.com/ergoplatform/sigma-rust/pull/334

**Comment by greenhat** [comment]
Done in #334. Bounty is sent.
