### ISSUE TITLE
[200 SigmaUSD] Implement logical XOR `^` op 

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#333]
- Add enum `ergotree_ir::mir::bin_op::LogicalOp` with `Xor` variant and move  `And`, `Or` from `RelationOp` there as well;
- Add `Xor` enum variant handling in `ergotree_interpreter::eval::bin_op`;

Reference Scala version:
IR node and eval - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/b60edae20f2af3352e4064d139d45a15fc507f7d/sigmastate/src/main/scala/sigmastate/trees.scala#L1294-L1312

**Comment by ApexTheory** [comment]
I have started on this issue.

**Comment by greenhat** [comment]
Done in #349 . Bounty is sent.
