### ISSUE TITLE
[150 SigmaUSD] Implement `Address::Pay2Sh` (Pay-to-Script-Hash)

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#337]
Reference implementation in Scala - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/00ffd5514cb8410c0646f5e10f51e383515fcb67/sigmastate/src/main/scala/org/ergoplatform/ErgoAddress.scala#L133-L177

**Comment by ApexTheory** [comment]
I have started on this issue.

**Comment by greenhat** [comment]
Done in #407

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
