### ISSUE TITLE
[150 SigmaUSD] Implement unary `~` (bit inversion) op

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#355]
Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. 

### Serialization
- Implement `Arbitrary` trait and add serialization roundtrip PBT test for this node;

### Evaluation
- Implement `Evaluable` trait in `ergotree-interpreter` crate;
- Add evaluation tests;

Check out similar `Negation` op [implementation](https://github.com/ergoplatform/sigma-rust/blob/125a102cdf263dfa3a20629731dc931efdfe462d/ergotree-ir/src/mir/negation.rs#L9-L14)
Check out the detailed implementation instructions for `Append`(`Coll`) op in  #301

Scala reference implementation:
IR node - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/b60edae20f2af3352e4064d139d45a15fc507f7d/sigmastate/src/main/scala/sigmastate/trees.scala#L943-L952
Serialization - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/b60edae20f2af3352e4064d139d45a15fc507f7d/sigmastate/src/main/scala/sigmastate/serialization/ValueSerializer.scala#L150-L150

**Comment by kettlebell** [comment]
Hi, I've made a PR for this issue.

**Comment by greenhat** [comment]
Done in #389. @kettlebell Great job! Please contact me in our Discord https://discord.gg/kj7s7nb to receive your bounty. Also, please leave your Discord username in a comment to this issue to confirm your identity on Discord.

**Comment by kettlebell** [comment]
My discord username is TimL#0815. Thank you!

**Comment by greenhat** [comment]
Bounty is sent! Thank you!
