### ISSUE TITLE
[150 SigmaUSD] Implement `XorOf` IR node (XOR for collection of booleans)

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#356]
Check out similar `And` IR node - https://github.com/ergoplatform/sigma-rust/blob/4784e17cf026844d40536c1da4ac20231de1ad55/ergotree-ir/src/mir/and.rs#L14-L20

Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. 

### Serialization
- Implement `Arbitrary` trait and add serialization roundtrip PBT test for this node;

### Evaluation
- Implement `Evaluable` trait in `ergotree-interpreter` crate;
- Add evaluation tests;

Check out the detailed implementation instructions for `Append`(`Coll`) op in  #301

Scala reference implementation:
IR node - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/0c5c5b515ccb452536e440469b56d763d5ba30ec/sigmastate/src/main/scala/sigmastate/trees.scala#L348-L375
Serialization - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/0c5c5b515ccb452536e440469b56d763d5ba30ec/sigmastate/src/main/scala/sigmastate/serialization/transformers/LogicalTransformerSerializer.scala#L11-L22 (the same as for `And` IR node).

**Comment by ApexTheory** [comment]
PR open https://github.com/ergoplatform/sigma-rust/pull/379

**Comment by greenhat** [comment]
Done in #379. Bounty is sent.
