### ISSUE TITLE
[150 SigmaUSD] Implement `Coll.patch` method

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#357]
- Add `SMethod` to `ergotree-ir::types::scoll`(method id is 19); 
- Add `EvalFn` in `ertotree-interpreter::eval::scoll` and include it in `ergotree-interpreter::eval::smethod_eval_fn`

See existing method implementations in `scoll` and `sbox` for examples;

Reference Scala version:
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/0c5c5b515ccb452536e440469b56d763d5ba30ec/sigmastate/src/main/scala/sigmastate/types.scala#L1585-L1599

**Comment by ApexTheory** [comment]
Figured I'd finish off the rest of the Collection ops.  I have added this implementation to my updateMany PR.
