### ISSUE TITLE
[150 SigmaUSD] Implement `Coll.updateMany` method

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#359]
- Add `SMethod` to `ergotree-ir::types::scoll`(method id is 21); 
- Add `EvalFn` in `ertotree-interpreter::eval::scoll` and include it in `ergotree-interpreter::eval::smethod_eval_fn`

See existing method implementations in `scoll` and `sbox` for examples;

Reference Scala version:
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/0c5c5b515ccb452536e440469b56d763d5ba30ec/sigmastate/src/main/scala/sigmastate/types.scala#L1615-L1627

**Comment by ApexTheory** [comment]
I have started on this issue.

**Comment by greenhat** [comment]
Done in #376. Bounty is sent.
