### ISSUE TITLE
[500 SigmaUSD] Distributed signatures support

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#367]
References:
[EIP-11](https://github.com/ergoplatform/eips/pull/8)
[Improved distributed signatures](https://www.ergoforum.org/t/improved-distributed-signatures/366)

New code should be in `prover::multi_sig` module.

#### Generate commitments
`fn generate_commitments(tx_context: TransactionContext, state_context: &ErgoStateContext) -> Result<TransactionHintsBag, _> ` function should be an equivalent of `wallet/generateCommitments` node API call, see implementation at https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/ergo-wallet/src/main/scala/org/ergoplatform/wallet/interpreter/ErgoProvingInterpreter.scala#L182-L222
`TransactionHintsBag` type should be an equivalent of https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/ergo-wallet/src/main/scala/org/ergoplatform/wallet/interpreter/TransactionHintsBag.scala#L5

#### Extract hints from signed(invalid) transaction
`fn extract_hints(tx_context: TransactionContext, state_context: &ErgoStateContext, real_secrets_to_extract: Vec<SigmaBoolean>, simulated_secrets_to_extract: Vec<SigmaBoolean>) -> Result<TransactionHintsBag, _>` should be an equivalent of `script/extractHints` node API call, see implementation at https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/ergo-wallet/src/main/scala/org/ergoplatform/wallet/interpreter/ErgoProvingInterpreter.scala#L224-L263

#### Hints support in prover and tx signing
- Check how hints are used in prover and implement the missing parts compared to the Scala reference implementation at https://github.com/ScorexFoundation/sigmastate-interpreter/blob/455d4a3b5a82eec9301be89019d8ea675386474a/sigmastate/src/main/scala/sigmastate/interpreter/ProverInterpreter.scala#L68-L103
- add `tx_hints: TransactionHintsBag` parameter to `Wallet::sign_*` methods and pass it down to prover (as `HintsBag`);

#### Wasm API. 
- Expose `TransactionHintsBag` type via wrapper;
- Add `tx_hints: TransactionHintsBag` parameters to `Wallet::sign_*` methods;
- Expose `generate_commitments` and `extract_hints` (passing serialized SigmaBooleans) functions.

#### Testing.
- implement test scenarios from https://github.com/ScorexFoundation/sigmastate-interpreter/blob/prepare-v5.0-evaluator/sigmastate/src/test/scala/sigmastate/utxo/DistributedSigSpecification.scala
- tests for `generate_commitments` should be implemented after https://github.com/ScorexFoundation/sigmastate-interpreter/blob/455d4a3b5a82eec9301be89019d8ea675386474a/sigmastate/src/test/scala/sigmastate/utxo/ProverSpecification.scala#L17-L58

**Comment by sahandzou** [comment]
UPDATE: multi-sig test with two signers passed.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
