### ISSUE TITLE
Missing serialization for Ledger support

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#384]
- TokenId::as_bytes()
- Constant::sigma_serialize_bytes()
- BoxId::as_bytes()
- rename ErgoTree::to_bytes() to ErgoTree::sigma_serialize_bytes()
- BoxValue and TokenAmounts to big-endian bytes
- ErgoBox:: serialized_registers (count and serialized registers)
- UnsignedTransaction::get_distinct_token_ids() return [TokenId]
- ContextExtension::sigma_serialize_bytes
- make Transaction from UnsignedTransaction + [ProofBytes]

**Comment by ypopovych** [comment]
Found more missed pieces.
`ErgoBox::tx_id` and `ErgoBox::index` can't be obtained from JS (full Ergo Box has them). They are needed for the `Attest Input` call.
