### ISSUE TITLE
[150 SigmaUSD] `Box.bytesWithoutRef` method's IR node (`ExtractBytesWithNoRef`)

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#400]
Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. 
Similar to the existing `ExtractBytes` IR node but without the transaction id and the index in the output.

### Serialization
- Implement `Arbitrary` trait and add serialization roundtrip PBT test for this node;

### Evaluation
- Implement `Evaluable` trait in `ergotree-interpreter` crate;
- Add new method in `IrErgoBox::bytesWithoutRef`
- Add evaluation tests;

Check out the existing IR node implementation (`ExtractBytes`) for details.

Check out the detailed implementation instructions for `Append` op in  #301

Reference Scala version:
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/utxo/transformers.scala#L437-L456

**Comment by ross-weir** [comment]
I'm making a start on this one

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
