### ISSUE TITLE
[100 SigmaUSD] `Context.selfBoxIndex` method

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#401]
- Add `SMethod` to `ergotree-ir::types::scontext`(method id is 8); 
- Add `EvalFn` in `ertotree-interpreter::eval::scontext` and include it in `ergotree-interpreter::eval::smethod_eval_fn`. Implementation details: return index of `Context::self_box` in `Context::inputs`.

See existing method implementations in `scoll` and `sbox` for examples;

**Comment by ross-weir** [comment]
Howdy 👋 

I'm going to have a shot at this one

**Comment by greenhat** [comment]
Done in #405. @ross-weir Great job! Please contact me (@greenhat) in our Discord https://discord.gg/kj7s7nb to receive your bounty. Also, please leave your Discord username in a comment to this issue to confirm your identity on Discord.

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
