### ISSUE TITLE
[200 SigmaUSD] `Downcast` IR node for numeric types

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#402]
Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. 
Similar to the existing `Upcast` IR node.

Reference Scala implementation:
IR node - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/trees.scala#L568-L587
For evaluation implementation details see `SNumeric.downcast` https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/types.scala#L775-L781 implementations for numeric types (`SInt`, etc.)

**Comment by ApexTheory** [comment]
I have started on this.

**Comment by greenhat** [comment]
Done in #408

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
