### ISSUE TITLE
[250 SigmaUSD] `SubstConstants` IR node

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#403]
Create a new struct in a separate module(file) in `mir` module and add it to `Expr` enum. Implement serialization and evaluation.

Doc comment from the reference Scala implementation (see link below):
> Transforms serialized bytes of `ErgoTree` with segregated constants by replacing constants at given positions with new values. This operation allows using serialized scripts as pre-defined templates. The typical usage is "check that output box have proposition equal to given script bytes, where `minerPk` (`constants(0)`) is replaced with `currentMinerPk`".  Each constant in the original `scriptBytes` have `SType` serialized before actual data.
> During substitution each value from `newValues` is checked to be an instance of the corresponding type.
> This means, the constants during substitution cannot change their types.

Reference Scala implementation:
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/trees.scala#L746-L799

**Comment by kettlebell** [comment]
I've started on this one.

**Comment by kettlebell** [comment]
Hi @greenhat, I've got an initial working implementation of `SubstConstants` but there are some differences with how it's done in the scala implementation.

`SubstConstants::new_values` represents the `Value`s to be substituted. The scala version is able to convert each of these `Value`s  into a `Constant` instance, which then allows for pushing into an empty `ConstantStore` (seen here: https://github.com/ScorexFoundation/sigmastate-interpreter/blob/fada073b82a16a928c457693b888da4c0310aca6/sigmastate/src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala#L261-L273).

Is it essential to pass the `Value` into the `ConstantStore` and pull it out as a `Constant` like it's done in scala? I've opted to write functions that computes a `SType` for any given `Value` (to check types before substitution) and then serialize it manually as a `Constant` as described by the ErgoTree spec.

**Comment by greenhat** [comment]
> Hi @greenhat, I've got an initial working implementation of `SubstConstants` but there are some differences with how it's done in the scala implementation.
> 
> `SubstConstants::new_values` represents the `Value`s to be substituted. The scala version is able to convert each of these `Value`s into a `Constant` instance, which then allows for pushing into an empty `ConstantStore` (seen here: https://github.com/ScorexFoundation/sigmastate-interpreter/blob/fada073b82a16a928c457693b888da4c0310aca6/sigmastate/src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala#L261-L273).
> 
> Is it essential to pass the `Value` into the `ConstantStore` and pull it out as a `Constant` like it's done in scala? I've opted to write functions that computes a `SType` for any given `Value` (to check types before substitution) and then serialize it manually as a `Constant` as described by the ErgoTree spec. Thanks.

I'm not sure I get the question. Scala's `Value` is an equivalent of our `Expr`. `TransformingSigmaBuilder.liftAny(v)` call is transforming what is essentially our `Value` (evaluation result) into a constant expression (our `Constant`).
I see in the PR that quite a bit of `ErgoTree` internals(header, version, has_size, etc) are leaked into `SubstConstants` evaluation code. I'd rather keep them in `ErgoTree` with `SubstConstants` eval treating it like a black box.

**Comment by kettlebell** [comment]
Thanks a lot, that clears things up. I can greatly simplify the PR.

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
