### ISSUE TITLE
[400 SigmaUSD] `AvlTree.insert` operation

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#411]
Create `AvlTreeData` struct and use in `Value::AvlTree(AvlTreeData)` and in `Literal::AvlTree(AvlTreeData)` and implement serialization (`SigmaSerializable` trait).
Scala reference implementation - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/AvlTreeData.scala#L42-L101

Create `savltree` modules for AvlTree methods definitions and evaluation similar to the existing `sbox` modules.
Add `AvlTree.insert` method in `savltree` module.
Scala reference implementation - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/types.scala#L2232-L2281

Use [`BatchAvlVerifier`](https://github.com/knizhnik/scorex_crypto_avltree/blob/36a0b47742d9d8f749ce95d2a794be88a03d13ec/src/batch_avl_verifier.rs#L8-L33) from https://crates.io/crates/scorex_crypto_avltree crate.

Use the existing `ADDigest` type for tree digest.

**Comment by kettlebell** [comment]
Starting on this issue.

**Comment by kettlebell** [comment]
Hi @greenhat, just letting you know about an issue with `ADDigest`. `Digest` is defined in and used by `ergo-lib`. `ergotree-ir` also requires `Digest`(through `ADDigest`) for the AVL tree. The problem is `ergo-lib` already depends quite heavily on `ergotree-ir`.

In my draft PR I just copied some of the types. A possible solution is to move `Digest` (with `Base16EncodedBytes` and `Base16DecodedBytes`) to another crate (`sigma-util`?). What do you think?

**Comment by greenhat** [comment]
> Hi @greenhat, just letting you know about an issue with `ADDigest`. `Digest` is defined in and used by `ergo-lib`. `ergotree-ir` also requires `Digest`(through `ADDigest`) for the AVL tree. The problem is `ergo-lib` already depends quite heavily on `ergotree-ir`.
> 
> In my draft PR I just copied some of the types. A possible solution is to move `Digest` (with `Base16EncodedBytes` and `Base16DecodedBytes`) to another crate (`sigma-util`?). What do you think?

I'm moving a lot of types from ergo-lib to ergotree-ir in https://github.com/ergoplatform/sigma-rust/pull/397 and Digest is among them. Use a copy as a workaround until it's merged and then we switch.

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
