### ISSUE TITLE
[150 SigmaUSD] Define `PreHeader` `STypeCompanion` with properties

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#420]
from #418
PreHeader properties definitions in `spreheader` module (see `sheader` module for examples). Define `SMethod` for each property.
Reference Scala implementation - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/types.scala#L2497-L2528

**Comment by ross-weir** [comment]
Hey!

I'm starting on this one

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
