### ISSUE TITLE
[300 SigmaUSD] AvlTree properties

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#425]
Implement `SMethod`(in `types::savltree`) and evaluation (in `eval::savltree`) of the following properties and methods:
- digest
- enabledOperations
- keyLength
- valueLengthOpt
- isInsertAllowed
- isUpdateAllowed
- isRemoveAllowed
- updateOperations
- updateDigest

Reference Scala implementation - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/types.scala#L2018-L2101
and
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala#L128-L150

**Comment by kettlebell** [comment]
Starting this one.

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
