### ISSUE TITLE
[100 SigmaUSD] `treeLookup` predefined function for AVL tree key lookup

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#438]
Create `TreeLookup` IR node. Evaluation is similar to the existing `AvlTree.get` method.

Reference Scala implementation - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/c863a9b1a82589e47b15f76f3affdb30a475e740/sigmastate/src/main/scala/sigmastate/trees.scala#L1411-L1433

**Comment by ApexTheory** [comment]
I will take this one as it is very similar to get
