### ISSUE TITLE
[150 SigmaUSD] Handle `TransactionContext::boxes_to_spend` order != `TransactionContext::spending_tx::inputs` order (same for data inputs)

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#453]
### `TransactionContext`
Make `TransactionContext::boxes_to_spend` and `data_boxes` private (+ use `TxIoVec` type) exposing them via getters and add checking ctor `new` failing if an id from `UnsignedTransaction::inputs` is not found in `boxes_to_spend` and an id from `UnsignedTransaction::data_inputs` is not found in `data_boxes`. 

### `signing::make_context`
- Find `self_box` by first finding it's id in `TransactionContext::spending_tx::inputs`;
- Make `Context::inputs` by mapping `TransactionContext::spending_tx::inputs` and finding boxes for input ids in `TransactionContext::boxes_to_spend`;
- Make `Context::data_inputs` by mapping `TransactionContext::spending_tx::data_inputs` and finding boxes for data input ids in `TransactionContext::data_boxes`;

### Testing
A good regression test would be to pass `boxes_to_spend` and `data_boxes` in reversed order of `TransactionContext::spending_tx::inputs` and `data_inputs` and check that `Context::self_box`, `inputs` and `data_inputs` are in correctorder (the same as in `TransactionContext::spending_tx`).

**Comment by kettlebell** [comment]
@greenhat You require that `TransactionContext::boxes_to_spend` and `data_boxes` use `TxIoVec`. Should I also make the change for `Context::inputs` and `Context::data_inputs` (it'll have downstream effects on `coll_[filter|fold|map]`)?

**Comment by greenhat** [comment]
> @greenhat You require that `TransactionContext::boxes_to_spend` and `data_boxes` use `TxIoVec`. Should I also make the change for `Context::inputs` and `Context::data_inputs` (~it'll have downstream effects on `coll_[filter|fold|map]`~ Only affects prop-tests in those modules)?

Good question! `Context` is more like the interpreter's internal representation and since in the ErgoScript/ErgoTree type system, there is no such thing as bounded vector/collection we don't get any benefits in the evaluation code from using `TxIoVec`. However, using `TxIoVec` in `Context` protects us from using incorrect quantities, and given that `Context` can be constructed not only from `TransactionContext` I think it's a good idea to use `TxIoVec` in here.
