### ISSUE TITLE
[50 SigmaUSD] `BoxSelection::boxes` cannot be empty

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#463]
### Motivation
In the error-less box selection `BoxSelection::boxes` cannot be empty. At least one box is required. 

### Solution
Use `BoundedVec` to ensure non-empty `BoxSelection::boxes`.
`pub type SelectedBoxes<T> = BoundedVec<T, 1, { u16::MAX as usize }>;` should suffice since tx inputs are limited to `u16::MAX`.

**Comment by Venoox** [comment]
So I need to change boxes type to SelectedBoxes<T> which is a BoundedVec and then I also need to change where BoxSelection is being created to include `.try_into().unwrap()`. Is there a better way without try_into?

**Comment by greenhat** [comment]
> So I need to change boxes type to SelectedBoxes which is a BoundedVec and then I also need to change where BoxSelection is being created to include `.try_into().unwrap()`. Is there a better way without try_into?

The reason for having try_into is to force error handling, so unwrap should only be used in tests or in compile-time defined constants that are checked in tests.

**Comment by greenhat** [comment]
Bounty is sent. Thank you!
