### ISSUE TITLE
[800 SigmaUSD] Arithmetic operations and polynomial interpolation over Galois fields GF(2^192)

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#473]
### Implementation details
Extract https://github.com/ergoplatform/sigma-rust/blob/develop/ergotree-interpreter/src/sigma_protocol/gf2_192.rs and https://github.com/ergoplatform/sigma-rust/blob/develop/ergotree-interpreter/src/sigma_protocol/gf2_192poly.rs into a separate crate `gf2_192` and implement according to existing implementation in Scala https://github.com/ScorexFoundation/sigmastate-interpreter/blob/prepare-v5.0-evaluator/sigmastate/src/main/java/gf2t/GF2_192.java , https://github.com/ScorexFoundation/sigmastate-interpreter/blob/prepare-v5.0-evaluator/sigmastate/src/main/java/gf2t/GF2_192_Poly.java

### Testing 
Implement tests according to the tests in Scala version in https://github.com/ScorexFoundation/sigmastate-interpreter/blob/prepare-v5.0-evaluator/sigmastate/src/test/java/gf2t/GF2_192Test.java

### References
https://github.com/reyzin/GF2t

Existing Rust implementation for Galois fields GF(2^256):
https://github.com/djsweet/galois_2p8
https://github.com/geky/gf256

**Comment by ApexTheory** [comment]
I can take this one.

**Comment by kettlebell** [comment]
Starting this one!

**Comment by kettlebell** [comment]
@greenhat Rust allows us to define operators like + and * for custom types. Would you like to have such syntactic sugar for the `gf2_192` types?

**Comment by greenhat** [comment]
> @greenhat Rust allows us to define operators like + and * for custom types. Would you like to have such syntactic sugar for the `gf2_192` types?

Sounds nice! Yes, please.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
