### ISSUE TITLE
[50 SigmaUSD] Fix `Downcast` eval tests and convert them to proptest along with `Upcast`

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#474]
`to_byte` test failed on CI - https://github.com/ergoplatform/sigma-rust/runs/4202100586?check_suite_focus=true . I presume it was due to `v_byte` being zero. 

- Fix the `to_byte` test for this case and check that other tests do not exhibit this behavior;
- Convert `Downcast` and `Upcast` test to proptest;

**Comment by SethDusek** [comment]
I'd like to take this one.

**Comment by ApexTheory** [comment]
Oops, looks like my bug 👎 Sorry

**Comment by greenhat** [comment]
> Oops, looks like my bug -1 Sorry

No worries! We all make mistakes. I often look at my old code and ask myself "Who wrote it? It should not work". :)

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
