### ISSUE TITLE
[100 SigmaUSD] Serialization for ergo-p2p

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#477]
In to sigma-ser crate add `ScorexSerializable` trait with `scorex_serialize` and `scorex_parse` methods similar to `SigmaSerializable` trait and implement helper `scorex_serialize_bytes` and `scorex_parse_bytes`. Parametrize with `ReadSigmaVlqExt` and `WriteSigmaVlqExt` as reader/writer.
Add `put_short_string` and `get_short_string` methods for `*SigmaVlqExt` for `String` shorter than 256 bytes. In the implementation, first store length in bytes as u8 and then string as bytes. See Scala implementation - https://github.com/ScorexFoundation/scorex-util/blob/00827a0a56a84f1ccb44b78aa92b00e72c8c8efb/src/main/scala/scorex/util/serialization/VLQWriter.scala#L150-L162

**Comment by SethDusek** [comment]
I'd like to take this one.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
