### ISSUE TITLE
[200 SigmaUSD] Peer management

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#479]
Create the following types in ergo-p2p crate:
- `PeerSpec`
Ergo node implementation - https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/src/main/scala/scorex/core/network/PeerSpec.scala#L11-L27

- `PeerInfo`
Ergo node implementation - https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/src/main/scala/scorex/core/network/peer/PeerInfo.scala#L8-L17

Implement serialization for the types above by implementing `ScorexSerializable` trait from sigma-ser (after #477 is implemented).

Create `PeerDatabase` trait and `InMemoryPeerDatabase` implementation with the following methods:
- `get_peer_by_addr`;
- `add_or_update_peer`;
- `remove_peer`;
- `known_peers`;

See Ergo node implementation - https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/src/main/scala/scorex/core/network/peer/InMemoryPeerDatabase.scala#L14 for details. Ignore blacklisting and penalizing peers methods since we don't need them now.

**Comment by ross-weir** [comment]
I'm making a start on this one

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
