### ISSUE TITLE
[100 SigmaUSD] Move Header type from ergotree-ir to ergo-chain-types crate

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#488]
Along with JSON serialization and `Arbitrary` implementation (behind `arbitrary` feature).

**Comment by hanbu97** [comment]
Working on this one.

**Comment by hanbu97** [comment]
It seems much easier and cleaner to mergo ergo-chain-types logic to ergotree-ir, and wrap them outside. Otherwise, a lot of serde, even mir parts should be seperated from ergootree-ir, in case cyclic dependency.

**Comment by hanbu97** [comment]
@greenhat

**Comment by greenhat** [comment]
> It seems much easier and cleaner to mergo ergo-chain-types logic to ergotree-ir, and wrap them outside. Otherwise, a lot of serde, even mir parts should be seperated from ergootree-ir, in case cyclic dependency.

Is it because of `AutolykosSolution` (`EcPoint`)? That might be a showstopper. ergo-chain-types are meant to be lower in dependency graph than ergotree-ir, so if it's too much effort we probably should leave it as is. Could you push your code as a draft PR so could take a look?

**Comment by kettlebell** [comment]
@hanbu97 are you still working on this issue? If not, I'd like to work on this.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
