### ISSUE TITLE
[100 SigmaUSD] Create PoPowHeader type

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#489]
In ergo-nipopow crate. Implement binary (ScorexSerializable trait) and JSON serialization. Use `Header` type from ergotree-ir (or from ergo-chain-types if #488 is implemented).
Scala reference implementation - https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/src/main/scala/org/ergoplatform/modifiers/history/popow/PoPowHeader.scala#L13-L83

**Comment by ross-weir** [comment]
I'm going to work on this one 👍

**Comment by ApexTheory** [comment]
Hi @ross-weir any updates on this?

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
