### ISSUE TITLE
[100 SigmaUSD] Add NipopowProof type

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#490]
Scala reference implementation -
https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/src/main/scala/org/ergoplatform/modifiers/history/popow/NipopowProof.scala#L25-L30
(ignore NipopowAlgos and skip NipopowProof methods)

In ergo-nipopow crate implement binary (implement ScorexSerializable trait) and JSON
serialization.

**Comment by ApexTheory** [comment]
I am starting on this one.

**Comment by kettlebell** [comment]
Looking into this, I think I've completed this issue as part of https://github.com/ergoplatform/sigma-rust/pull/517/ except for roundtrip testing. @ApexTheory it's been quite a while since your last comment, is it ok if I finish this up?

**Comment by kettlebell** [comment]
I had a chat with @ApexTheory on discord, confirming the handover.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
