### ISSUE TITLE
[1000 SigmaUSD] NiPoPoW proof verification

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#499]
Required for SPV workflow step 1.1 defined in https://github.com/ergoplatform/sigma-rust/issues/495

See [KMZ17](https://fc20.ifca.ai/preproceedings/74.pdf) for reference.

Implement `NipopowProof` in ergo-nipopow crate equivalent of the reference Scala implementation - https://github.com/ergoplatform/ergo/blob/c320810c498bca25a44197840c7c5a86440c5906/src/main/scala/org/ergoplatform/modifiers/history/popow/NipopowProof.scala#L9-L157 including binary and JSON serialization and everything in the call hierarchy starting from `NipopowProof.isBetterThan` and all the way down including `NipopowAlgos.bestArg` and `AutolykosPowScheme.powHit`.

Implement `NipopowVerifier` equivalent of the reference Scala implementation - https://github.com/ergoplatform/ergo/blob/c320810c498bca25a44197840c7c5a86440c5906/src/main/scala/org/ergoplatform/local/NipopowVerifier.scala#L8-L27

**EDIT**: Both `NipopowProof` and `NipopowVerifier` (with `process` and `best_proof`) should be exposed in Wasm/iOS API.

**Comment by kettlebell** [comment]
Going to tackle this one.

**Comment by kettlebell** [comment]
I've yet to put through a draft PR, but I've finished studying the KMZ17 paper and I'm going down this rabbit hole with how Ergo and Bitcoin encode the difficulty targets.

**Comment by greenhat** [comment]
No worries! Take your time! I appreciate you're taking a thorough approach.

**Comment by greenhat** [comment]
Hey! I'm sorry, I totally forgot that it should be exposed in Wasm/iOS. I've added an EDIT in the description.

**Comment by kettlebell** [comment]
Sure, no problem!

**Comment by kettlebell** [comment]
Hi @greenhat, I'm looking at serialization of `Header` under `ergotree-ir` and I see that it doesn't yet implement `ScorexSerializable`. I've already implemented binary serialization without POW-solution as part of `NipopowProof`, so I'll finish it. @ApexTheory if you haven't already implemented it in your work on #489 feel free to stub it.

Also, I notice that JSON (de)serialization of `Header` ignores the POW-solution fields. Should we implement this?

**Comment by greenhat** [comment]
> Hi @greenhat, I'm looking at serialization of `Header` under `ergotree-ir` and I see that it doesn't yet implement `ScorexSerializable`. I've already implemented binary serialization without POW-solution as part of `NipopowProof`, so I'll finish it. @ApexTheory if you haven't already implemented it in your work on #489 feel free to stub it.
> 

Sounds great!

> Also, I notice that JSON (de)serialization of `Header` ignores the POW-solution fields. Should we implement this?

Good catch! Yes, please.

**Comment by ApexTheory** [comment]
Hi @kettlebell, yes I just came across the `ScorexSerializable` gap in my own ticket.  I will just stub the method in my code then, thanks.

**Comment by kettlebell** [comment]
@greenhat I've got a JSON (de)serialization working for `Header`, but I want to clarify one thing with you. The `pow_distance` field is represented by a `BigInt`. Now the `serde` encoding for this is `(sign, absolute-value)`, which isn't compatible with the JSON representation that Ergo uses.

I had a look at `serde_json`, and it looks like it handles `u64` at most. So I did a custom serialization through `u64`, then to `BigInt`. Is it safe to assume to `pow_distance` can't take a value beyond the max of `u64`? Thanks.

**Comment by greenhat** [comment]
> @greenhat I've got a JSON (de)serialization working for `Header`, but I want to clarify one thing with you. The `pow_distance` field is represented by a `BigInt`. Now the `serde` encoding for this is `(sign, absolute-value)`, which isn't compatible with the JSON representation that Ergo uses.
> 
> I had a look at `serde_json`, and it looks like it handles `u64` at most. So I did a custom serialization through `u64`, then to `BigInt`. Is it safe to assume to `pow_distance` can't take a value beyond the max of `u64`? Thanks.

From the description, at https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/mining/AutolykosSolution.scala#L22-L23 I'm afraid it might not fit in u64.

Just to be sure we're on the same page, `pow_distance` is supposed to be encoded as `d` in `Header.powSolutions.d` field as I see in the node - https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/modifiers/history/header/Header.scala#L149
with `BigInt.toString` - https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/http/api/ApiCodecs.scala#L61-L63 , right?

**Comment by kettlebell** [comment]
> Just to be sure we're on the same page, `pow_distance` is supposed to be encoded as `d` in `Header.powSolutions.d` field as I see in the node - https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/modifiers/history/header/Header.scala#L149 with `BigInt.toString` - https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/http/api/ApiCodecs.scala#L61-L63 , right?

Yes that's right. I've learnt that the JSON spec doesn't specify limits on the Number type. Also `serde_json` has an `arbitrary_precision` flag to process such numbers. I'll figure it out. Thanks a lot for the references!

**Comment by kettlebell** [comment]
I've completed (de)serialization of the PoW solution parameters. It can deserialize `pow_distance` from both number and string representation. However I can only serialize `pow_distance` into a JSON string. I don't think it's a problem because I found that the `circe` library deserializes a `BigInt` from both a JSON Number and string (https://github.com/circe/circe/blob/1c8a5a03d0ccd403e577d6fce04e2308ba957891/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L857) 

I needed to use the `arbitrary_precision` feature of `serde_json`, which leads to the code hitting a bug (https://github.com/serde-rs/json/issues/740). Basically when the `arbitrary_precision` feature is used, `serde` can't deserialize integer types within 'untagged' enums. The workaround is to first deserialize into `serde_json::Number`, then manually convert. It affects 3 places in `ergotree-ir` (`Votes`, `BoxValue` and `TokenAmount`) and I've made sure that the test suite passes locally.

There is also a cost to using `arbitrary_precision`; `serde_json` represents every number as a string internally. I don't think it's a big deal here. I hope it's ok with you.

**Comment by kettlebell** [comment]
I'm working on `ScorexSerialization` for `Header`, adapting code here: https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/modifiers/history/header/HeaderSerializer.scala#L15-L76.

I notice that the scala code doesn't serialize/deserialize `Header.id`. Now I dug around and saw this: https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/modifiers/history/header/Header.scala#L59

I'm guessing that `id` is equal to the Blake2b256 hash of the concatenation of:
  - the serialization of everything in `serializeWithoutPow` and
  - the serialization of `AutolykosSolution`
and that this is the final field to be serialized.

Is this correct?

**Comment by greenhat** [comment]
> I've completed (de)serialization of the PoW solution parameters. It can deserialize `pow_distance` from both number and string representation. However I can only serialize `pow_distance` into a JSON string. I don't think it's a problem because I found that the `circe` library deserializes a `BigInt` from both a JSON Number and string (https://github.com/circe/circe/blob/1c8a5a03d0ccd403e577d6fce04e2308ba957891/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L857)
> 
> I needed to use the `arbitrary_precision` feature of `serde_json`, which leads to the code hitting a bug ([serde-rs/json#740](https://github.com/serde-rs/json/issues/740)). Basically when the `arbitrary_precision` feature is used, `serde` can't deserialize integer types within 'untagged' enums. The workaround is to first deserialize into `serde_json::Number`, then manually convert. It affects 3 places in `ergotree-ir` (`Votes`, `BoxValue` and `TokenAmount`) and I've made sure that the test suite passes locally.
> 
> There is also a cost to using `arbitrary_precision`; `serde_json` represents every number as a string internally. I don't think it's a big deal here. I hope it's ok with you.

Sounds good! Thanks for the detailed explanation!

**Comment by greenhat** [comment]
> I'm working on `ScorexSerialization` for `Header`, adapting code here: https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/modifiers/history/header/HeaderSerializer.scala#L15-L76.
> 
> I notice that the scala code doesn't serialize/deserialize `Header.id` directly there. Now I dug around and saw this: https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/modifiers/history/header/Header.scala#L59
> 
> I'm guessing that `id` is equal to the Blake2b256 hash of the concatenation of:
> 
>     * the serialization of everything in `serializeWithoutPow` and
> 
>     * the serialization of `AutolykosSolution`
> 
> 
> and ~that this is the final field to be serialized~ it doesn't need to be serialized.
> 
> Is this correct?

Yes, you're right! `Header.bytes` is essentially a call to `serialize` - https://github.com/ergoplatform/ergo/blob/5d98f9f063d2ff80d3c97739a7d22b817751c43d/src/main/scala/org/ergoplatform/modifiers/history/header/HeaderSerializer.scala#L16-L17

**Comment by greenhat** [comment]
Due to the increased complexity of the task (proof generation, chain generation for tests) the bounty is increased to 1500 SigmaUSD.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
