### ISSUE TITLE
[350 SigmaUSD] `MerkleProof` verification

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#515]
In a new `ergo-merkle-tree` crate:

Implement `MerkleProof` type equivalent to the reference Scala implementation - 
https://github.com/input-output-hk/scrypto/blob/2237785131ee0946e44d6a5aec2ef0fc0731efce/src/main/scala/scorex/crypto/authds/merkle/MerkleProof.scala#L7-L26 including `MerkleProo.valid()` method.

Implement JSON serialization according to the reference node implementation - https://github.com/ergoplatform/ergo/blob/66d6f3c395a1d6dc2cb40671405c6202c80693d8/src/main/scala/org/ergoplatform/http/api/ApiCodecs.scala#L54-L59

Since we don't have `MerkleProof` generation implemented let's get the proof from the node manually.
Here is the approximate workflow:
- manually pick any block and any tx id in it;
- get a `MerkleProof` from any node via `/blocks/{headerId}/proofFor/{txId}`;
- hardcode JSON response in the test;
- call `MerkleProof.valid(header.transactionRoot)`

`MerkleProof` type and its `valid` method should be exposed in WASM(JS)/iOS(Swift) API layers.

**Comment by SethDusek** [comment]
I'd like to take this one.

**Comment by CapsuleCorpp** [comment]
let's do this brenda !

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
