### ISSUE TITLE
[100 SigmaUSD] Eval for SGLOBAL methods

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#519]
Implement in new `ergotree_interpreter::eval::sglobal` module evaluation (`EvalFn`) for `groupGenerator` and `xor` for byte arrays methods:
- `groupGenerator` should eval to `dlog_group::generator()`.
- `xor` eval should be identical to the existing `Xor` IR node eval - https://github.com/ergoplatform/sigma-rust/blob/0200f346b0aee2952ca82fd5d27cb08e7c228c5e/ergotree-interpreter/src/eval/xor.rs#L17-L34
- add case for `sglobal::TYPE_CODE` in `eval::smethod_eval_fb` - https://github.com/ergoplatform/sigma-rust/blob/0200f346b0aee2952ca82fd5d27cb08e7c228c5e/ergotree-interpreter/src/eval.rs#L211

See `eval::scontext` for examples of how to implement a static `EvalFn` value.

**Comment by sahandzou** [comment]
I will take it!

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
