### ISSUE TITLE
[100 SigmaUSD] Run ergo-lib-wasm JS tests in a headless browser on CI

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#522]
Now we run the JS tests `bindings/ergo-lib-wasm/tests/*.js` with nodejs. New tests for `ergo-rest` to test REST API requests are browser-only (use Fetch API) so we need to run them on a headless browser. Besides that, it's a good idea to run all our JS tests in the browser as well as on nodejs.
Add a job step similar to https://github.com/ergoplatform/sigma-rust/blob/ac64723b5af42ff967ca51cc4a915539e178150b/.github/workflows/js_tests.yml#L44-L48 for running all our JS tests in a browser.
Also, we need a way to limit certain tests to be run only in a browser. We can put them in a separate file/folder or do a check in runtime.

**Comment by hanbu97** [comment]
It works. [pull request](https://github.com/ergoplatform/sigma-rust/pull/543)

**Comment by greenhat** [comment]
Done in #543

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
