### ISSUE TITLE
[1000 SigmaUSD] PoPowHeader Interlink Batch Merkle Proof verification

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#536]
Please be aware that most of the Scala reference implementation referenced below is still WIP in https://github.com/ergoplatform/ergo/pull/1526 with the issue [here](https://github.com/ergoplatform/ergo/issues/1384)

Add `BatchMerkleProof` type in `ergo_merkle_tree` crate and implement its validation against an expected root hash, see Scala [reference implementation](https://github.com/input-output-hk/scrypto/blob/88fc0ee4e1eecf3d63e5986487b243b3548bb707/src/main/scala/scorex/crypto/authds/merkle/BatchMerkleProof.scala#L11-L121) with tests equivalent to [tests in Scala implementation](https://github.com/input-output-hk/scrypto/blob/88fc0ee4e1eecf3d63e5986487b243b3548bb707/src/test/scala/scorex/crypto/authds/merkle/MerkleTreeSpecification.scala#L52-L89)
f
Add `interlinks_proof: BatchMerkleProof` property to `PoPowHeader` struct (implemented in https://github.com/ergoplatform/sigma-rust/issues/489). Implement binary serialization of the `BatchMerkleProof` type equivalent to the Scala [reference implementation](https://github.com/input-output-hk/scrypto/blob/88fc0ee4e1eecf3d63e5986487b243b3548bb707/src/main/scala/scorex/crypto/authds/merkle/serialization/BatchMerkleProofSerializer.scala#L10-L81) and JSON serialization equivalent to Scala [implementation](https://github.com/ergoplatform/ergo/blob/9114d7149338326e4c018aee91405c200381f6e9/src/main/scala/org/ergoplatform/modifiers/history/popow/PoPowHeader.scala#L75-L111)
Implement binary serialization tests equivalent to Scala [implementation](https://github.com/input-output-hk/scrypto/blob/88fc0ee4e1eecf3d63e5986487b243b3548bb707/src/test/scala/scorex/crypto/authds/merkle/serialization/BatchMerkleProofSerializerSpecification.scala#L12-L112) and a roundtrip test for JSON serialization/deserialization.

Add `NipopowProof::has_valid_proofs() -> bool` verification, see Scala [reference implementation](https://github.com/ergoplatform/ergo/blob/9114d7149338326e4c018aee91405c200381f6e9/src/main/scala/org/ergoplatform/modifiers/history/popow/NipopowProof.scala#L90-L96) which checks headers in prefix and suffix head to have valid interlinks proofs.
Implement tests equivalent to the ones [implemented](https://github.com/ergoplatform/ergo/blob/9114d7149338326e4c018aee91405c200381f6e9/src/test/scala/org/ergoplatform/modifiers/history/PoPowHeaderSpec.scala#L7-L22) in Scala 
The `NipopowProof` type is implemented in https://github.com/ergoplatform/sigma-rust/pull/517

**Comment by SethDusek** [comment]
I'd like to take this one

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
