### ISSUE TITLE
[100 SigmaUSD] Wasm and Swift bindings for the arbitrary message signing and verification

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#542]
### Implementation (DONE)

Add `wallet:signing::sign_message` with the following signature:
```rust
/// Sign arbitrary message under a key representing a statement provable via a sigma-protocol.
/// A statement can be a simple ProveDlog (PK) or a complex sigma conjectives tree
pub fn sign_message(prover: &dyn Prover, sigma_tree: SigmaBoolean, msg: &[u8],) -> Result<Vec<u8>, ProverError> 
```
which should just call the modified `Prover::generate_proof` with removed `ctx_ext` param and returning `ProofBytes` instead of `ProverResult` (should be constructed at the call sites):
```rust
    fn generate_proof(
        &self,
        sigmabool: SigmaBoolean,
        message: &[u8],
        hints_bag: &HintsBag,
    ) -> Result<ProofBytes, ProverError> {
```
Add `Wallet::sign_message` which should just be a wrapper of `wallet::signing::sign_message` (see existing `Wallet::sign_*`).

Add `verifier::verify_signature` with the following signature:
```rust
pub fn verify_signature(sigma_tree: SigmaBoolean, message: &[u8], signature: &[u8]) -> Result<bool, VerifierError>
```
implementation of which should be extracted from `Verifier::verify` (the part after `cprop`).

### Testing (DONE)
Since we're extracting/calling existing code covered with tests a simple smoke test should be enough. Something similar to `verifier::tests::test_prover_verifier_p2pk`.

## Wasm API

Add `wallet::sigma_message_using_p2pk` with the following signature:
```rust
/// Sign arbitrary an message using a P2PK address
pub fn sign_message_using_p2pk(&self, address: Address, message: &[u8]) -> Result<Vec<u8>, JsValue> 
```
Create new `verifier::verify_signature(address: Address, message: &[u8], signature: &[u8]) -> Result<bool, JsValue>`

Create a smoke test in `ergo-lib-wasm/tests` JS tests. 

## Swift API
Add `Wallet.signMessage(withP2PK addr: Address, message: ByteArray) throws -> ByteArray` with all needed underlying functions in `ergo-lib-core-c` and `ergo-lib-c` (see existing `Wallet.signTransaction` for examples).
Create `Verifier.swift` module with a function `verifySignature(address: Address, message: ByteArray, signature: ByteArray) throws -> Bool` with all needed underlying functions in `ergo-lib-core-c` and `ergo-lib-c`
Create a smoke test in `ergo-lib-ios/Tests/ErgoLibTests`.

**Comment by greenhat** [comment]
The 100 SigmaUSD bounty is sent for #553 PR with the implementation but without the Wasm and Swift bindings.

**Comment by kettlebell** [comment]
I will complete the bindings.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
