### ISSUE TITLE
[300 SigmaUSD] Example SPV workflow with NiPoPoW

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#569]
Implement in JS/TS the workflow described in #495 for a chosen payment on mainnet. Pick any payment(box) on the mainnet.
This example aims to show the developers how they can check that a payment was made using SPV API with NiPoPoW.
Ideally, we'd want that workflow implemented as a test against hardcoded nodes.

**Comment by kettlebell** [comment]
I will work on this.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
