### ISSUE TITLE
Fix vendored-deps crates so ergo-rest can be published

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#570]
On publishing dependencies that are specified by `path` are taken by `version` with `path` ignored.
I see two options:
1) Embed the vendored crates source files as modules of ergo-rest crate;
2) Publish vendored crates under an altered name;

I'd try 1) first and use 2) only as last resort.

**Comment by greenhat** [comment]
@kettlebell I totally forgot about `path` dependencies when I reviewed your PR. Could you please take care of this?

**Comment by kettlebell** [comment]
Sure no problem, will be able to in a few hours.
