### ISSUE TITLE
[500 SigmaUSD] `peer_discovery` REST API has problems on Chrome

### ISSUE THREAD

**Issue by kettlebell** [ergoplatform/sigma-rust#581]
The current implementation of `peer_discovery` doesn't quite work on Chrome (it works perfectly on Firefox and tokio). Basically it cannot discover anywhere near the amount of existing active nodes (it mostly finds 0 or 1). I tried my best to find the underlying cause, but no dice. Although the function returns without error, there is also a really bad bug that results: after calling `peer_discovery` any subsequent HTTP requests fail, with `reqwest` reporting that the request times out.

## Mitigation
I tweaked the value of many parameters and found a mitigation for this. My educated guess from these experiments is that Chrome has an issue where it can't handle too many concurrent promises. So referring to my schematic from the code, `peer_discovery` works as follows:

 - Task 1 is responsible for tracking which nodes are active/inactive and making sure that any
   given ergo node is queried exactly once.
 - Task 2's job is to wait for a URL from task 1, make the actual HTTP requests to that URL, and
   to report the result back to task 1.
```text
                             <ergo node URL>
              __________________________________________________
             |                                                  |
             |                                                  v
 /----------------------\                   /----------------------\
 | 1. Track node status |                   | 2. HTTP request task |
 \----------------------/                   \----------------------/
             ^                                                  |
             |__________________________________________________|
               <active node| non-active node| list of peers>   
```

The solution for Chrome is to restrict the number of URLs sent to task 2. More specifically we must make the following changes:
 - The global timeout interval is key. For chrome this needs to be **no more than 1.5 seconds**. Anything longer and the bug described above appears.
 - The timeout isn't strict anymore. When it triggers we wait for any in-flight URLs to be checked, then we return.
 - The queue that task 2 uses to buffer incoming URLs is set to length of 50.
 - Surprisingly, the timeout interval for each individual HTTP request to each peer node needs to be about 6 seconds (this even affects Firefox). Lower values results in missing some active nodes. This problem doesn't occur with the `tokio` version: things work fine setting the interval to 2 seconds.

Now what this means is that Chrome can't discover all the available nodes (it can get about 13). The following table gives rough results by timeout length when using Firefox:

|Global timeout(sec)| # peers reached| # active peers discovered| 
|--|---|--|
|[1.0, 4.4] | ~260 | ~13|
| [4.5, ..) | ~560| ~16|

The results are like a step function. For example any interval between 1 to 4.4 seconds gives us 13 active nodes.

**Comment by greenhat** [comment]
Thank you for the very thorough explanation! Sounds good! I'm adding bounty for this task.

>     * The queue that task 2 uses to buffer incoming URLs is set to length of 50.

I suppose this buffer(50) is essentially the limit of concurrent requests, right? So we could fine-tune it later on.

**Comment by kettlebell** [comment]
> I'm adding bounty for this task.

Thank you!

> I suppose this buffer(50) is essentially the limit of concurrent requests, right? So we could fine-tune it later on.

The buffer smooths the flow of data between the 2 tasks, which is interacting in a tight loop. If the buffer is too small, task 2 can't get URLs-to-check fast enough which in turn clogs up task 1 as it will accumulate too many `peer` URLs. I've been running more tests and 50 might even be a bit large (performance plateaus past a certain size).

It looks like the browsers are now capable of massive concurrent requests, Chrome can do 256 whilst Firefox is > 1000 (according to tests described here: https://stackoverflow.com/a/30064610). Now to date there's 616 ergo nodes out there, so we can go beyond Chrome's limit. But I throttled the max requests <= 256 and the bug still persists on Chrome, so the problem lies elsewhere.

I'll dig into this some more and I'll consolidate all the parameters into a struct for easy fine-tuning.

**Comment by greenhat** [comment]
Got it. Thank you!

**Comment by greenhat** [comment]
@TimL Whoa! This is quite the rabbit hole indeed! I appreciate you digging into this! I agree with your conclusions. Thank you for taking care of this!

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
