### ISSUE TITLE
Box id parsed from JSON differs from calculated

### ISSUE THREAD

**Issue by abchrisxyz** [ergoplatform/sigma-rust#587]
First output of this [tx](https://explorer.ergoplatform.com/en/transactions/3a8555a63904527a70b4f1896d4c265dff86152db5837820398c5531db143ac2) is not deserializable from json, as returned by the node. Running into `"Box id parsed from JSON differs from calculated from box serialized bytes"`

To reproduce:

```
// main.rs
use ergotree_ir::chain::ergo_box::ErgoBox;

fn main() {
    let json = r#"
    {
        "boxId": "551242f664faa1dae9d8788b94813945fbfacf0c7be11dd044cb4d0430ca0427",
        "value": 1000000,
        "ergoTree": "cd07021a8e6f59fd4a",
        "assets": [],
        "creationHeight": 545682,
        "additionalRegisters": {},
        "transactionId": "3a8555a63904527a70b4f1896d4c265dff86152db5837820398c5531db143ac2",
        "index": 0
      }
    "#;

    let _eb: ErgoBox = serde_json::from_str(json).unwrap();
}
```

```
// cargo.toml
...
[dependencies]
ergotree-ir = "0.17.0"
serde_json = "1.0"
```

**Comment by greenhat** [comment]
Well, besides language version 5 for which I cannot find any references in sigmastate, the header has bit 6 set (GZip compression?) and bit 7 set (header contains more than one byte). I believe we don't have support for this anywhere. With the overall size of the ergo tree way too small to be holding any PK I suspect that this ergo tree is invalid and cannot be parsed.

**Comment by abchrisxyz** [comment]
Thanks for looking so quickly into it. So you're saying it is/was a node issue (i.e. accepting the invalid ergo tree in the first place) ?

**Comment by greenhat** [comment]
> Thanks for looking so quickly into it. So you're saying it is/was a node issue (i.e. accepting the invalid ergo tree in the first place) ?

It seems so. I'm going to check the node code, but I cannot recall that we have any check for ergo tree in an output box. 
Anyway, ergo-lib should do better and recognize that this ergo tree is unparseable and store it as bytes in the box. This way we parse the box from JSON but it'll have an unparsed ergo tree.

**Comment by abchrisxyz** [comment]
The thing that puzzles me is how the explorer backend assigns address `4MQyMKvMbnCJG3aJ` to that box. Might be a whole different issue though.

**Comment by abchrisxyz** [comment]
Hmm, seems that tree would give address `3okPuYvFMHix`. Anyways, that's not related to this issue. Thanks for your help.
