### ISSUE TITLE
Increase minimum ergo node version from 4.0.28 to 4.0.100 for SPV workflow tests

### ISSUE THREAD

**Issue by kettlebell** [ergoplatform/sigma-rust#638]
Due to the proposed EIP-37 hard-fork, the SPV tests were breaking since a number of nodes have already upgraded and we use string-comparison for ergo node versions (so that "4.0.100" is judged to be less than "4.0.28"). EIP-37 looks like it will pass, so let's bump up the version to 4.0.100.

**Comment by greenhat** [comment]
Sounds good! Thank you for taking care of this!
