### ISSUE TITLE
examples/create-transaction-demo failed to sign tx

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#650]
The following error during the tx signing was reported on discord - 
https://discord.com/channels/668903786361651200/729692906209673257/1040286614125035630

```
Transaction signing error: Prover error (tx input index 0): Failed on step2(prover does not have enough witnesses to perform the proof)
```

I suspect the `changeSk` secret key used in wallet instead of a master key derived from the seed:
https://github.com/ergoplatform/sigma-rust/blob/e6483c68c6f1c1beb768d5c6a0e11fac18e26335/bindings/ergo-lib-wasm/examples/create-transaction-demo/index.ts#L111-L115

**Comment by ross-weir** [comment]
Not sure - the example as it is works for me. Did they provide the JSON anywhere?

In one of the first messages they mention a error:

```
Failed to parse BlockHeader from JSON string ... with error: invalid digit found in string at line 1 column 814 
There is a number with scientific notation - "d":7.799422127220499e+70
```

Which looks like a valid error, they said they removed `d` from `powSolutions` to get around it - not sure if that can manifest the tx signing error they're seeing

**Comment by greenhat** [comment]
Oh, I get it. The testnet used in the example is long gone. :) @ross-weir never mind, sorry for bothering you.

**Comment by ross-weir** [comment]
@greenhat no problems, feel free to ping me whenever - I'm still happy to help when I have the time :-)
