### ISSUE TITLE
Block deser fail due to ErgoBox deser error (box id check)

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#677]
Cannot deserialize block 2ad5af788bfd1b92790eadb42a300ad4fc38aaaba599a43574b1ea45d5d9dee4 with sigma-rust: Getting Box id parsed from JSON differs from calculated from box serialized bytes

ergo-lib = { git = "https://github.com/ergoplatform/sigma-rust", rev = "62b8dedc0577f01551b6f8be4585f39b028d70f7", features = ["json", "arbitrary"] }

**Comment by oskin1** [comment]
One more failing block b17847c0c523660b13d707396ab8301fa3c8a545ddc5acf9ec2803cc2cbb3ef5

**Comment by greenhat** [comment]
in block `2ad5af788bfd1b92790eadb42a300ad4fc38aaaba599a43574b1ea45d5d9dee4` the failing box is `551242f664faa1dae9d8788b94813945fbfacf0c7be11dd044cb4d0430ca0427` reported in #587

**Comment by greenhat** [comment]
In block `b17847c0c523660b13d707396ab8301fa3c8a545ddc5acf9ec2803cc2cbb3ef5` a tx has an input with `ContextExtension` items decoded from JSON out of order which leads to an incorrect tx id.
Extracted to #685

**Comment by greenhat** [comment]
Fixed in #684 and #687
