### ISSUE TITLE
Tx verification

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#703]
We have `verify_tx_input_proof,` and we're missing the whole tx verification.

**Comment by rang0fish** [comment]
Hi greenhat
I've noted the absence of transaction verification mentioned in the issue. I'm want to take on this task and work on implementing the missing components.

To ensure that I address the requirements accurately, could you please provide more details on the specific functionalities and criteria needed for the complete transaction verification process?
