### ISSUE TITLE
Add Boolean.toByte

### ISSUE THREAD

**Issue by sethdusek** [ergoplatform/sigma-rust#764]
Add a method (.toByte) to Boolean in ergotree-interpreter

- Add .toByte method to Boolean (convert true to 1, false to 0)
- Make .toByte only activate when activated version is > 3
- Implement tests for .toByte, along with versioning tests (scripts that use .toByte should fail if activated version is <= 3)

Reference PR: https://github.com/ScorexFoundation/sigmastate-interpreter/pull/940
Reference Issue: https://github.com/ScorexFoundation/sigmastate-interpreter/issues/931

**Comment by kushti** [comment]
Likely will not be included in 6.0
