### ISSUE TITLE
Add Global.fromBigEndianBytes

### ISSUE THREAD

**Issue by sethdusek** [ergoplatform/sigma-rust#786]
A new Global.fromBigEndianBytes[TNum] method is implemented in this PR, which can parse big-endian two's complement binary representation of TNum type.
 
 example:
 
 ```
 {
   val l = 1088800L
   val ba = l.toBytes
   Global.fromBigEndianBytes[Long](ba) == l
 }
 ```
 
Reference PR: https://github.com/ergoplatform/sigmastate-interpreter/pull/1013

**Comment by sebastianrof** [comment]
Hi
I hope you're doing well. I am new to Sigma-Rust and have just made my first contribution (#795) by submitting a pull request for this issue. However, I've noticed that the latest develop branch has a failed GitHub Action, which may affect the CI/CD process for my PR.

**Comment by sethdusek** [comment]
@sebastianrof Please send your discord username and ergo wallet address here

**Comment by sebastianrof** [comment]
@SethDusek Thank You!
my Ergo Wallet Address is : 9gmSX3F4A4c3wZ5djFC6KU2rcqZMB5SjTazgRx8kENSi93gaKZQ
and My Discord Username is: sebantof

**Comment by sebastianrof** [comment]
@SethDusek Any update sir?

**Comment by sethdusek** [comment]
Sent. Thank you!
