### ISSUE TITLE
Simplify *Error to JsValue conversion

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#97]
The goal is to avoid `.map_err(|e| JsValue::from_str(&format!("{}", e)))` in WASM layer. Ideally, I see implementing `From/Into` for errors and use `?` but orphan rules should not allow that.

See code example - https://github.com/ergoplatform/sigma-rust/blob/develop/bindings/ergo-lib-wasm/src/contract.rs#L11-L20

**Comment by kettlebell** [comment]
To get around the orphan rules we can wrap `JsValue` and write a conversion function as follows:
```rust
struct JsValueWrap(JsValue);

impl From<SigmaParsingError> for JsValueWrap {
    fn from(e: SigmaParsingError) -> Self {
        JsValueWrap(JsValue::from_str(&format!("{}", e)))
    }
}

fn conv<S: Into<JsValueWrap>>(s: S) -> JsValue {
    s.into().0
}
```

The resulting call will be `.map_err(conv)`. What do you think?

**Comment by greenhat** [comment]
@kettlebell `.map_err(conv)` looks good. I like it!

**Comment by kettlebell** [comment]
PR #393 addresses this issue. There are a number of instances where the `Debug` trait is used to render the `JsValue` (`JsValue::from_str(&format! {"{:?}"`). One such error `TryExtractFromError` also implements the `Display` trait.

In any case I didn't change them in case some other library depends on these particular renderings of the error.

**Comment by greenhat** [comment]
> PR #393 addresses this issue. There are a number of instances where the `Debug` trait is used to render the `JsValue` (`JsValue::from_str(&format! {"{:?}"`). One such error `TryExtractFromError` also implements the `Display` trait.
> 
> In any case I didn't change them in case some other library depends on these particular renderings of the error.

I think it's safe to change them as well. I'm not aware of any library that relays on these renderings of the error.

**Comment by kettlebell** [comment]
Cool. PR #394 should close this issue out.
